---
- name: download current libpng source
  get_url: url=http://sourceforge.net/projects/libpng/files/libpng16/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz
  when: libpng_ver | match("1\.6\.2[4-5]")

- name: download older libpng source
  get_url: url=http://sourceforge.net/projects/libpng/files/libpng16/older-releases/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz
  when: libpng_ver | match("1\.6\.[0-9](?![0-9])|1\.6\.1[0-9]|1\.6\.2[0-3]")

- name: unzip libpng source
  unarchive: src={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/libpng-{{ libpng_ver }} copy=no

- name: configure libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && ./configure

- name: make libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make 

- name: install libpng
  become: yes
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make install
